AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Master template for global services and configurations across all the stacks

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    ConstraintDescription: Environment is not valid

  Appname:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
    ParameterGroups:
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken


Resources:
  AlamrsTopic:
    Type: AWS::SNS::Topic

  AlamrsTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${Appname}-${Environment}-alarmsTopic-arn
      Tags:
        app: !Ref Appname
        env: !Ref Environment
        type: parameter
        description: Alarms topic Arn
      Type: String
      Value: !Ref AlamrsTopic


  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !If [isProduction, 90, 7]
      LogGroupName: ${Appname}-${Environment}-logGroup

  LogGroupName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${Appname}-${Environment}-logGroup-name
      Tags:
        app: !Ref Appname
        env: !Ref Environment
        type: parameter
        description: Services log group name
      Type: String
      Value: !Ref LogGroup

  Appname:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Appname
      Tags:
        app: !Ref Appname
        env: !Ref Environment
        type: parameter
        description: Services log group name
      Type: String
      Value: !Ref Appname

  # Token should be in form '{"token":"123abc"}'
  GithhubSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Appname}-${Environment}-github
      Description: Contain mainly a GithubToken for CodePipeline
      Tags:
        - Key: app
          Value: !Ref Appname
        - Key: env
          Value: !Ref Environment
        - Key: type
          Value: security

Outputs:
  AlarmsTopicArn:
    Description: Topic for all the alarms
    Value: !GetAtt AlamrsTopicArn.Value

  LogGroupName:
    Description: Global log group name
    Value: !GetAtt LogGroupName.Value
